//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenFinal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Visita
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        [MaxLength(200)]
        public string Motivo { get; set; }

        [Display(Name = "Fecha Visita")]
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Debe seleccionar una fecha")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyy}", ApplyFormatInEditMode = true)]
        public System.DateTime Fecha_Visita { get; set; }

        [Display(Name = "Hora Entrada")]
        [DataType(DataType.Time)]
        [Required(ErrorMessage = "Debe seleccionar una hora de entrada")]
        public string Hora_Entrada { get; set; }

        [Display(Name = "Hora Salida")]
        [DataType(DataType.Time)]
        [Required(ErrorMessage = "Debe seleccionar una hora de salida")]
        public string Hora_Salida { get; set; }

        [Display(Name = "Visitante")]
        [Required(ErrorMessage = "Este campo es obligatorio")]
        [MaxLength(100)]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "Debe seleccionar una opción")]
        [Display(Name = "Empleado")]
        public int Contacto { get; set; }
    
        public virtual Contactos Contactos { get; set; }
    }
}
